api.current_version=${project.version}
api.min_version=1.0
db.version=31
# 文件存储路径
# file.storage.path=/mnt/d/SoftwareEngineering/Teedy/data/docs

# # H2数据库持久化
# db.url=jdbc:h2:/mnt/d/SoftwareEngineering/Teedy/data/teedydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
# db.user=teedy
# db.password=teedy